engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python:
          python_version: 3
  eslint:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "D"
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
